# Generated by Django 4.0.3 on 2022-04-29 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodbankRegistrationModel',
            fields=[
                ('Bloodbank_id', models.AutoField(primary_key=True, serialize=False)),
                ('Bloodname', models.TextField(help_text='Enter Your Name', max_length=50)),
                ('Bloodaddress', models.TextField(help_text='Enter Your address', max_length=50)),
                ('Bloodmobilenumber', models.BigIntegerField(help_text='Enter Your mobilenumber', max_length=50)),
                ('Bloodemail', models.EmailField(help_text='Enter gmail', max_length=50)),
                ('Bloodpassword', models.CharField(help_text='enter Password', max_length=200)),
                ('Bloodreg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'bloodbank_registration_details',
            },
        ),
        migrations.CreateModel(
            name='BloodbankSendRequestModel',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('bloodbank_name', models.TextField(help_text='Enter Your hospitalName', max_length=50)),
                ('bloodbank_mobilenumber', models.BigIntegerField(help_text='Enter Your mobilenumber', max_length=50)),
                ('bloodbank_bloodgroup_requried', models.CharField(help_text='Enter Your bloodgroup', max_length=50)),
                ('bloodbank_blood_requried_ml', models.CharField(help_text='Enter Your bloodrequried ml', max_length=50)),
                ('bloodbank_send_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('bloodbank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodbankapp.bloodbankregistrationmodel')),
            ],
            options={
                'db_table': 'bloodbank_send_bloodrequest_details',
            },
        ),
    ]
