# Generated by Django 4.0.3 on 2022-05-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbanksendrequestmodel',
            name='hospital_id',
            field=models.CharField(help_text='hospital_id', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bloodbanksendrequestmodel',
            name='status',
            field=models.CharField(help_text='status', max_length=50, null=True),
        ),
    ]
