# Generated by Django 4.0.3 on 2022-05-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0002_bloodbanksendrequestmodel_hospital_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbanksendrequestmodel',
            name='bloodbank_id1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodbankapp.bloodbankregistrationmodel'),
        ),
        migrations.AlterField(
            model_name='bloodbanksendrequestmodel',
            name='bloodbank_id',
            field=models.CharField(help_text='hospital_id', max_length=50, null=True),
        ),
    ]
