# Generated by Django 4.0.3 on 2022-05-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0003_bloodbanksendrequestmodel_bloodbank_id1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbankregistrationmodel',
            name='bloodbank_status',
            field=models.CharField(help_text='bloodbank_status', max_length=200, null=True),
        ),
    ]
