# Generated by Django 4.0.3 on 2022-05-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0004_bloodbankregistrationmodel_bloodbank_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbankregistrationmodel',
            name='upload_bloodbank',
            field=models.ImageField(help_text=' upload_bloodbank image ', max_length=50, null=True, upload_to=''),
        ),
    ]
