# Generated by Django 4.0.3 on 2022-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0008_alter_bloodbankregistrationmodel_bloodbank_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbanksendrequestmodel',
            name='b_status',
            field=models.CharField(default='Pending', help_text='status', max_length=50),
        ),
    ]
