# Generated by Django 4.0.3 on 2022-05-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0010_alter_bloodbanksendrequestmodel_bloodbank_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbanksendrequestmodel',
            name='Bloodemail',
            field=models.EmailField(help_text='Enter gmail', max_length=254, null=True),
        ),
    ]
