# Generated by Django 4.0.3 on 2022-05-06 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NgoCampConductModel',
            fields=[
                ('ngo_camp_id', models.AutoField(primary_key=True, serialize=False)),
                ('ngo_camp_centername', models.CharField(help_text='Enter Your centername', max_length=50)),
                ('ngo_camp_location', models.TextField(help_text='Enter Your location', max_length=50)),
                ('ngo_conduct_time', models.TimeField(help_text='Enter time', max_length=50)),
                ('ngo_conduct_date', models.DateField(help_text='enter date', max_length=200)),
                ('ngo_reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ngo_conduct_camps_details',
            },
        ),
        migrations.CreateModel(
            name='NgoRegistrationModel',
            fields=[
                ('ngo_id', models.AutoField(primary_key=True, serialize=False)),
                ('ngo_name', models.TextField(help_text='Enter Your Name', max_length=50)),
                ('ngo_address', models.TextField(help_text='Enter Your address', max_length=50)),
                ('ngo_mobilenumber', models.BigIntegerField(help_text='Enter Your mobilenumber', max_length=50)),
                ('ngo_email', models.EmailField(help_text='Enter gmail', max_length=50)),
                ('ngo_password', models.CharField(help_text='enter Password', max_length=200)),
                ('ngo_reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ngo_registration_details',
            },
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('user_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_id', models.CharField(help_text='hospital_id', max_length=50, null=True)),
                ('bloodbank_id', models.CharField(help_text='bloodbank_id', max_length=50, null=True)),
                ('user_profile_name', models.TextField(help_text='Enter Your Name', max_length=50)),
                ('user_profile_bloodgroup', models.CharField(help_text='Enter Your bloodgroup', max_length=50)),
                ('user_profile_email', models.EmailField(help_text='Enter Your email', max_length=50)),
                ('user_profile_mobilenumber', models.BigIntegerField(help_text='Enter Your mobilenumber', max_length=50, null=True)),
                ('user_profile_blood', models.CharField(help_text='blood', max_length=50, null=True)),
                ('user_profile_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('user_profile_blood_donated_date', models.DateField(auto_now_add=True, null=True)),
                ('user_profile_certificate', models.CharField(help_text='certificate', max_length=50)),
                ('user_profile_donated_lastmonth', models.CharField(help_text='dontedlast months', max_length=50, null=True)),
                ('status', models.CharField(help_text='Status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_donate_request_details',
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(help_text='Enter Your Name', max_length=50)),
                ('user_bloodgroup', models.CharField(help_text='Enter Your bloodgroup', max_length=50)),
                ('user_email', models.EmailField(help_text='Enter Your email', max_length=50)),
                ('user_mobilenumber', models.BigIntegerField(help_text='Enter Your mobilenumber', max_length=50)),
                ('user_dateofbirth', models.DateField(help_text='Enter Your dateofbirth', max_length=50)),
                ('user_password', models.CharField(help_text='Enter Your password', max_length=50)),
                ('user_gender', models.CharField(help_text='Enter Your gender', max_length=50, null=True)),
                ('user_upload_profile', models.ImageField(help_text='Upload your image', max_length=50, null=True, upload_to='')),
                ('user_reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_registration_details',
            },
        ),
        migrations.CreateModel(
            name='UserReciptantModel',
            fields=[
                ('user_reciptant_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_reciptant_name', models.TextField(help_text='Enter Your Name', max_length=50)),
                ('user_reciptant_email', models.EmailField(help_text='Enter Your email', max_length=50)),
                ('user_reciptant_mobilenumber', models.BigIntegerField(help_text='Enter Your mobilenumber', max_length=50)),
                ('user_reciptant_requried_ml', models.CharField(help_text='enter requried ml', max_length=50, null=True)),
                ('user_reciptant_requried_bloodgroup', models.CharField(help_text='enter requried bloodgroup', max_length=50, null=True)),
                ('user_reciptant_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.userregistrationmodel')),
            ],
            options={
                'db_table': 'user_reciptant_request_details',
            },
        ),
    ]
