# Generated by Django 4.0.3 on 2022-05-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_userreciptantmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreciptantmodel',
            name='bloodbank_id',
            field=models.CharField(help_text='bloodbank_id', max_length=50, null=True),
        ),
    ]
