# Generated by Django 4.0.3 on 2022-05-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_ngoregistrationmodel_ngo_upload_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoregistrationmodel',
            old_name='ngo_upload_profile',
            new_name='ngo_upload_image',
        ),
    ]
