# Generated by Django 4.0.3 on 2022-05-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_rename_ngo_upload_profile_ngoregistrationmodel_ngo_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='user_profile_address',
            field=models.CharField(help_text='Enter donor address', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='user_address',
            field=models.TextField(help_text='Enter Your Address', max_length=50, null=True),
        ),
    ]
