# Generated by Django 4.0.3 on 2022-05-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_userprofilemodel_user_profile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngocampconductmodel',
            old_name='ngo_camp_centername',
            new_name='ngo_camp_name',
        ),
        migrations.AddField(
            model_name='ngocampconductmodel',
            name='ngo_camp_contact',
            field=models.CharField(help_text='Enter contact ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ngocampconductmodel',
            name='ngo_camp_person_name',
            field=models.CharField(help_text='Enter contact person name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ngocampconductmodel',
            name='ngo_conduct_end_time',
            field=models.TimeField(help_text='Enter time', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ngocampconductmodel',
            name='ngo_conduct_time',
            field=models.TimeField(help_text='Enter time', max_length=50, null=True),
        ),
    ]
