# Generated by Django 4.0.3 on 2022-05-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rename_ngo_camp_centername_ngocampconductmodel_ngo_camp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoregistrationmodel',
            name='ngo_status',
            field=models.CharField(help_text='Status', max_length=50, null=True),
        ),
    ]
