# Generated by Django 4.0.3 on 2022-05-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_ngoregistrationmodel_ngo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngocampconductmodel',
            name='bloodbank_id',
            field=models.CharField(help_text='bloodbank_id', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ngocampconductmodel',
            name='hospital_id',
            field=models.CharField(help_text='hospital_id', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ngocampconductmodel',
            name='status',
            field=models.CharField(default='Pending', help_text='Status', max_length=50, null=True),
        ),
    ]
