# Generated by Django 4.0.3 on 2022-05-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_ngocampconductmodel_bloodbank_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreciptantmodel',
            name='user_upload_profile',
            field=models.ImageField(help_text='Upload your image', max_length=50, null=True, upload_to=''),
        ),
    ]
