# Generated by Django 4.0.3 on 2022-05-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_userreciptantmodel_user_upload_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreciptantmodel',
            old_name='user_upload_profile',
            new_name='user_upload',
        ),
    ]
