# Generated by Django 4.0.3 on 2022-05-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_remove_userreciptantmodel_user_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoregistrationmodel',
            name='ngo_status',
            field=models.CharField(default='Pending', help_text='Status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='status',
            field=models.CharField(default='Pending', help_text='Status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userreciptantmodel',
            name='status',
            field=models.CharField(default='Pending', help_text='Status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='user_status',
            field=models.CharField(default='Pending', help_text='user_status', max_length=200, null=True),
        ),
    ]
