# Generated by Django 4.0.3 on 2022-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_alter_ngocampconductmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='p_status',
            field=models.CharField(default='Pending', help_text='status', max_length=50),
        ),
        migrations.AddField(
            model_name='userreciptantmodel',
            name='u_status',
            field=models.CharField(default='Pending', help_text='status', max_length=50),
        ),
    ]
