# Generated by Django 4.0.3 on 2022-05-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_alter_ngocampconductmodel_bloodbank_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='p_status',
            new_name='P_status',
        ),
    ]
