# Generated by Django 4.0.3 on 2022-05-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_rename_p_status_userprofilemodel_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngocampconductmodel',
            name='n_status',
            field=models.CharField(default='Pending', help_text='status', max_length=50),
        ),
    ]
