# Generated by Django 4.0.3 on 2022-05-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_ngocampconductmodel_n_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='bloodbank_id',
            field=models.IntegerField(default=0, help_text='bloodbank_id', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='hospital_id',
            field=models.IntegerField(default=0, help_text='hospital_id', max_length=50),
        ),
        migrations.AlterField(
            model_name='userreciptantmodel',
            name='bloodbank_id',
            field=models.IntegerField(default=0, help_text='bloodbank_id', max_length=50),
        ),
        migrations.AlterField(
            model_name='userreciptantmodel',
            name='hospital_id',
            field=models.IntegerField(default=0, help_text='hospital_id', max_length=50),
        ),
    ]
