# Generated by Django 4.0.3 on 2022-05-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_alter_userprofilemodel_bloodbank_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngocampconductmodel',
            name='ngo_email',
            field=models.EmailField(help_text='Enter gmail', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='user_email',
            field=models.EmailField(help_text='Enter Your email', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userreciptantmodel',
            name='user_email',
            field=models.EmailField(help_text='Enter Your email', max_length=50, null=True),
        ),
    ]
