# Generated by Django 4.0.3 on 2022-05-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_ngocampconductmodel_ngo_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='userreciptantmodel',
            name='user_email',
        ),
    ]
